name: "Check and build all packages"

on:
  pull_request:
  push:
    branches: [main]

jobs:
  build-all:
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm, macos-latest] # macos-13
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Check flake inputs
        uses: DeterminateSystems/flake-checker-action@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - run: nix flake check --all-systems
      - run: nix build .#zen-browser .#zen-browser-twilight
